### ISSUE TITLE
Fix dataset loading

### ISSUE THREAD

**Issue by thinkh** [Caleydo/taco_server#15]
@thinkh commented on [Mon Apr 16 2018](https://github.com/Caleydo/taco/issues/122)

* Release number or git hash: c749fd4c5ac061a5b545343ec03a5ff240b36839

### Steps to reproduce

1. Open https://taco.caleydoapp.org/#ds=Olympic%20Games%20Total%20Medals
2. Wait --> nothing will happen

### Observed behavior

![image](https://user-images.githubusercontent.com/5851088/38804864-2ccdeef4-4174-11e8-8faf-bb0f846714d7.png)

Some datasets are not loading and produce an internal server error. The server log looks like this:

```
10:45:49 ERROR taco_server.api: Exception on /compare/tacoServerOlympicGames1932TotalMedals/tacoServerOlympicGames1936TotalMedals/structure,structure,content,nochange/bar_chart [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/phovea/taco_server/api.py", line 67, in bar_chart
return diff_log(id1, id2, bins_row, bins_col, direction, operations)
File "/phovea/taco_server/api.py", line 45, in diff_log
json_result = diff_cache.get_ratios(id1, id2, direction, operations, br, bc)
File "/phovea/taco_server/src/diff_cache.py", line 140, in get_ratios
diffobj = get_diff_table(id1, id2, direction, ops, False)
File "/phovea/taco_server/src/diff_cache.py", line 97, in get_diff_table
diffobj = calc_diff(id1, id2, direction, all_ops)
File "/phovea/taco_server/src/diff_cache.py", line 215, in calc_diff
d = diff_finder.generate_diff(ops)
File "/phovea/taco_server/src/diff_finder.py", line 775, in generate_diff
has_structure)
File "/phovea/taco_server/src/diff_finder.py", line 831, in _compare_ids
apos = np.where(u_ids == j)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

### Expected behavior
* The datasets should load as expected.

**Comment by thinkh** [comment]
The problem occurred when the column labels have different length. For instance 1896 the maximum length is 18 characters, but for 1900 the maximum length is 20. Since the length was statically set in numpy array the longer string was cut. This way the `200m Backstroke Men` became `200m Backstroke M` and could not be matched in the later code (which caused the error).

The solution was to switch from `dtype=np.unicode_` to `dtype='object'` as described [here](https://stackoverflow.com/questions/14639496/python-numpy-array-of-arbitrary-length-strings#14639568).
